FROM ghcr.io/project-osrm/osrm-backend

# Install wget
RUN apt-get update && apt-get install -y wget osmium-tool \
    && rm -rf /var/lib/apt/lists/*

COPY *.sh /data/

RUN cd /data && /data/download-pbf.sh && /data/merge-pbf.sh && osrm-extract -p /opt/car.lua /data/merged.osm.pbf && osrm-partition /data/merged.osm && osrm-customize /data/merged.osm && rm /data/merged.osm.pbf

ENTRYPOINT [ "osrm-routed", "--algorithm", "mld" ]

CMD [ "/data/merged.osm" ]
